apiVersion: v1
kind: Service
metadata:
  name: {{ include "languagetool-chart.fullname" . }}
  annotations:
    {{- if .Values.service.googleInternal | default false }}
    cloud.google.com/load-balancer-type: "Internal"
    {{- end }}
  labels:
    {{- include "languagetool-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "languagetool-chart.selectorLabels" . | nindent 4 }}
